trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Dev
    displayName: "Build and Deploy to Dev"
    jobs:
      - template: templates/build-and-deploy-template.yml
        parameters:
          environment: "dev"
          acrSecretName: "Dev-ACR-Secret"
          acrLoginServer: "Dev-ACR-Login-Server"
          postgresHostSecret: "Dev-Postgres-Host"
          postgresDbSecret: "Dev-Postgres-DB"
          imageTag: "dev"

  - stage: Staging
    displayName: "Build and Deploy to Staging"
    dependsOn: Dev
    jobs:
      - template: templates/build-and-deploy-template.yml
        parameters:
          environment: "staging"
          acrSecretName: "Staging-ACR-Secret"
          acrLoginServer: "Staging-ACR-Login-Server"
          postgresHostSecret: "Staging-Postgres-Host"
          postgresDbSecret: "Staging-Postgres-DB"
          imageTag: "staging"

  - stage: Prod
    displayName: "Build and Deploy to Prod"
    dependsOn: Staging
    jobs:
      - template: templates/build-and-deploy-template.yml
        parameters:
          environment: "prod"
          acrSecretName: "Prod-ACR-Secret"
          acrLoginServer: "Prod-ACR-Login-Server"
          postgresHostSecret: "Prod-Postgres-Host"
          postgresDbSecret: "Prod-Postgres-DB"
          imageTag: "prod"
